name: eblox_annotation
description: A starting point for Dart libraries or applications.
version: 0.0.2
homepage: https://github.com/arcticfox1919/eblox

environment:
  sdk: '>=2.12.0 <3.0.0'


# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
